### ISSUE TITLE
Ruby images with preinstaled node images are not available

### ISSUE THREAD

**Issue by shiroyasha** [semaphoreci/docker-images#12]
Rails projects frequently require a preinstalled node version. We need convenience images that come with Node preinstalled.

I need the following images:

- semaphoreci/ruby:<ruby-version>-node

Example:

- semaphoreci/ruby:2.6.2-node

The installed Node version should be the either the latest release of Node, or the latest available in the repository.

**Comment by bogyo210** [comment]
Because of the nature of the renderer, the images look like semaphoreci/ruby-node:x.x.x
node version is 10.15.3
@CommanderK5 pls create the ruby-node repo on docker.com, so i can push to it.

**Comment by shiroyasha** [comment]
@bogyo210 I don't think that is a good practice. It will require additional guidance and documentation from our part. 

The pattern used in the docker community is to have additional dash separated options for an image in the repository. Example from official Postgres: `postgres:9.6`, `postgres:9.6-alpine`. Or from official Ruby: `ruby:2.2`, `ruby:2.2-slim`, `ruby:2.3-slim-alpine4.3`.

**Comment by bogyo210** [comment]
@CommanderK5 
Please delete the ruby version with tag : x.x.x.-node from https://hub.docker.com/r/semaphoreci/ruby/
TY
@shiroyasha 
Looks ok now

**Comment by shiroyasha** [comment]
Ack. I'll test out the images on the semaphore-ruby-rails example project today or tomorrow and will close the issue if everything works as expected.

**Comment by shiroyasha** [comment]
@bogyo210 please also check the following:

1. The comment on the bottom of the Dockerfile definitions says that it is installing Android. This is incorrect and instead the installation is adding node. https://github.com/semaphoreci/docker-images/blob/master/ruby/Dockerfile-ruby-2-6-2-ruby-node#L68

2. The name of the file is `Dockerfile-ruby-2-6-2-ruby-node`, while the non-node ones are called `Dockerfile-ruby-2-6-2`. Something is not right with this. I would expect the files to be called `Dockerfile-ruby-2-6-2-node`.

**Comment by shiroyasha** [comment]
Tested the image on a project. Works like a charm 👏 🍰 

https://github.com/semaphoreci-demos/semaphore-demo-ruby-rails/pull/3

---

@bogyo210 feel free to close the issue once the issues (1) and (2) from the previous comment are fixed.

**Comment by shiroyasha** [comment]
The names have been fixed. 🎉

Closing.
