### ISSUE TITLE
Haskell image with Stack

### ISSUE THREAD

**Issue by markoa** [semaphoreci/docker-images#13]
From here https://hub.docker.com/_/haskell:

1. This image ships a minimal Haskell toolchain (ghc and cabal-install) as well as the Stack tool
2. New users are encouraged to start with Stack.

Based on this, we need to provide a Haskell Docker image that comes with Stack preinstalled. We'll use it for an example project.

**Comment by bogyo210** [comment]
I can confirm that stack is installed inside the image.
With the following build commands :  
          - checkout
          - stack new my-project
          - cd my-project
          - stack setup
          - cp ../A.hs app/Main.hs
          - stack build
          - stack exec my-project-exe
Received the same output as with previous approach.

**Comment by markoa** [comment]
Thank you @bogyo210. This means that we actually don't need a new image.
