### ISSUE TITLE
Support all Android versions

### ISSUE THREAD

**Issue by shiroyasha** [semaphoreci/docker-images#15]
Currently, only an image tagged with `base` is available.

We need support for all android versions.

**Comment by CommanderK5** [comment]
I think this is a naming issue, currently we support multiple android sdk-s:
https://github.com/semaphoreci/docker-images/blob/master/android/Dockerfile-android-base#L97-L112

**Comment by shiroyasha** [comment]
Does it make sense to have one Docker Image per Android version? It seems more user friendly.

**Comment by CommanderK5** [comment]
I'll add images for all versions and a all-in-one as well, @shiroyasha is that OK?

**Comment by shiroyasha** [comment]
Yes. That would be perfect.

**Comment by CommanderK5** [comment]
Images deployed:
https://cloud.docker.com/u/semaphoreci/repository/docker/semaphoreci/android
