### ISSUE TITLE
Add node LTS to semaphoreci/android docker image

### ISSUE THREAD

**Issue by stajics** [semaphoreci/docker-images#38]
Add node LTS  to `semaphoreci/android` docker image needed for React Native boilerplate using Fastline. Node is needed to run `npm` commands needed for React Native.

**Comment by CommanderK5** [comment]
Hi @stajics,

Andorid images with node (10.x) variant are now available in semaphore docker hub:
https://hub.docker.com/r/semaphoreci/android

Following tags were added:
semaphoreci/android:25-node
semaphoreci/android:26-node
semaphoreci/android:27-node
semaphoreci/android:28-node
semaphoreci/android:29-node
semaphoreci/android:base-node

**Comment by stajics** [comment]
@CommanderK5 Can you add a emulator device like `Nexus_5X` or some other? There are no emulator devices installed atm
