### ISSUE TITLE
Need DockerImage for ruby version 2.5.1

### ISSUE THREAD

**Issue by harshil-shipmnts** [semaphoreci/docker-images#7]
I tried using ruby2.5.1 directly but it gives error while installing toolbox.

**Comment by CommanderK5** [comment]
Hi @harshil-shipmnts thank you for opening this issue.
I've added ruby2.5.1 to semaphoreci dockerhub repo - https://hub.docker.com/r/semaphoreci/ruby/tags

**Comment by harshil-shipmnts** [comment]
Thank you @CommanderK5
